server {
    listen 80;
    root /usr/share/nginx/html;
    location / { try_files $uri $uri/ =404; }
    location = /health { add_header Content-Type text/plain; return 200 'ok'; }
    location = /stub_status { stub_status; allow 127.0.0.1; allow 172.16.0.0/12; deny all; }
}
